package com.example.ui.theme

object LocalizedStrings {
    private val en = mapOf(
        "app_name" to "PayLink",
        "home" to "Home",
        "wallet" to "Wallet",
        "transfer" to "Transfer",
        "payments" to "Payments",
        "profile" to "Profile",
        "balance_title" to "Available Balance",
        "send_money" to "Send Money",
        "receive_money" to "Receive QR",
        "deposit" to "Deposit",
        "withdraw" to "Withdraw",
        "bill_payments" to "Pay Bills",
        "buy_airtime" to "Buy Airtime",
        "recent_transactions" to "Transaction History",
        "notifications" to "Notifications",
        "kyc_status" to "KYC Verification",
        "kyc_verified" to "Verified Account",
        "kyc_unverified" to "Unverified (Verify KYC)",
        "support" to "Live Support",
        "language_select" to "Language / Lugha",
        "biometrics" to "Biometric Login",
        "security_security" to "Advanced Security Mode",
        "scan_qr" to "Scan QR Pay",
        "qr_explanation" to "Show this QR code to some user to receive peer-to-peer payment instantly.",
        "phone_number" to "Phone Number",
        "full_name" to "Full Name",
        "email_address" to "Email Address",
        "pin_code" to "4-Digit PIN Code",
        "pin_confirm" to "Confirm 4-Digit PIN",
        "sign_in" to "Sign In",
        "sign_up" to "Register",
        "no_account" to "Don't have an account? Sign Up",
        "have_account" to "Already have an account? Sign In",
        "amount" to "Amount",
        "bank_select" to "Select Provider / Bank",
        "account_number" to "Recipient Number / Phone",
        "notes" to "Notes (Optional)",
        "security_pin" to "Enter Security PIN to Confirm",
        "confirm" to "Confirm Payment",
        "cancel" to "Cancel",
        "support_hint" to "Ask support a question (e.g., 'How to deposit?', 'Fees?')...",
        "kyc_doc" to "Select ID Document Type",
        "kyc_num" to "Document ID Number",
        "submit_kyc" to "Submit Verification",
        "empty_transactions" to "No transactions found yet.",
        "support_agent_greeting" to "Habari! Welcome to PayLink Live Support. Ask me anything about mobile money transfers, transaction fees, and account security. I can assist in English and Swahili!",
        "under_review" to "Your KYC is approved and active!",
        "fraud_alert" to "Security warning: Potential high-risk transfer detected. PayLink fraud scanner is active.",
        "invalid_credentials" to "Invalid phone or PIN. Try again.",
        "low_balance" to "Insufficient wallet balance for this request.",
        "quick_stats" to "Analytics & Stats",
        "money_in" to "Income",
        "money_out" to "Expenses",
        "deposit_success" to "Deposited successfully into your wallet.",
        "transfer_success" to "P2P Transfer completed successfully.",
        "withdraw_success" to "Withdrawn successfully from wallet.",
        "bill_success" to "Utility bill payment completed.",
        "airtime_success" to "Airtime purchased successfully.",
        "welcome_first" to "Welcome to PayLink! Secure your fintech wallet by enabling Biometric Login and verifying your KYC details in your Profile section."
    )

    private val sw = mapOf(
        "app_name" to "PayLink",
        "home" to "Nyumbani",
        "wallet" to "Mkoba",
        "transfer" to "Tuma Pesa",
        "payments" to "Malipo",
        "profile" to "Wasifu",
        "balance_title" to "Salio Lililopo",
        "send_money" to "Tuma Pesa",
        "receive_money" to "Pokea kwa QR",
        "deposit" to "Weka Pesa",
        "withdraw" to "Toa Pesa",
        "bill_payments" to "Lipia Bili",
        "buy_airtime" to "Nunua Muda wa Maongezi",
        "recent_transactions" to "Kumbukumbu ya Miamala",
        "notifications" to "Taarifa",
        "kyc_status" to "Uthibitisho wa KYC",
        "kyc_verified" to "Akaunti Imethibitishwa",
        "kyc_unverified" to "Haujathibitishwa (Thibitisha hapa)",
        "support" to "Msaada / Live Support",
        "language_select" to "Language / Lugha",
        "biometrics" to "Ulinzi wa Alama ya Vidole",
        "security_security" to "Hali Advanced ya Usalama",
        "scan_qr" to "Skena Lipa na QR",
        "qr_explanation" to "Onyesha hii QR kadi kwa mtumiaji mwingine ili upokee pesa haraka.",
        "phone_number" to "Namba ya Simu",
        "full_name" to "Majina Kamili",
        "email_address" to "Barua Pepe",
        "pin_code" to "Nambari ya Siri (PIN)",
        "pin_confirm" to "Thibitisha PIN yako",
        "sign_in" to "Ingia Akaunti",
        "sign_up" to "Jisajili",
        "no_account" to "Huna Akaunti? Jisajili",
        "have_account" to "Umeshajisajili? Ingia",
        "amount" to "Kiasi cha Pesa",
        "bank_select" to "Chagua Benki / Mtandao",
        "account_number" to "Namba ya Mpokeaji / Kadi",
        "notes" to "Maelezo ya Ziada (Si Lazima)",
        "security_pin" to "Weka PIN ya Usalama Kuthibitisha",
        "confirm" to "Thibitisha Malipo",
        "cancel" to "Ghairi",
        "support_hint" to "Uliza jambo (mfano, 'Viwango vya makato?', 'Jinsi ya kuweka pesa?')...",
        "kyc_doc" to "Chagua Aina ya Kitambulisho",
        "kyc_num" to "Namba ya Kitambulisho",
        "submit_kyc" to "Wasilisha Taarifa",
        "empty_transactions" to "Hakuna miamala iliyofanyika bado.",
        "support_agent_greeting" to "Habari! Karibu kwenye huduma ya usaidizi wa PayLink. Unaweza kuniuliza kuhusu jinsi ya kutuma pesa, makato ya miamala, au kuongeza usalama wa mkoba wako. Karibu kujadili!",
        "under_review" to "Hongera! Uthibitisho wako wa KYC umepitishwa kikamilifu!",
        "fraud_alert" to "Tahadhari ya usalama: Muamala una hatari ya udanganyifu. Mtambo wa PayLink upo macho.",
        "invalid_credentials" to "Namba ya simu au namba ya siri (PIN) sio sahihi. Jaribu tena.",
        "low_balance" to "Salio lako halitoshi kwa sasa kufanya muamala huu.",
        "quick_stats" to "Uchambuzi wa Salio",
        "money_in" to "Mapato",
        "money_out" to "Matumizi",
        "deposit_success" to "Pesa imewekwa kwa ufanisi kwenye wallet yako.",
        "transfer_success" to "Muamala wa kutuma pesa umekamilika vyema.",
        "withdraw_success" to "Pesa imetolewa kikamilifu kutoka kwenye wallet.",
        "bill_success" to "Malipo ya bili yamekamilika kikamilifu.",
        "airtime_success" to "Muda wa maongezi umenunuliwa kikamilifu.",
        "welcome_first" to "Karibu kwenye PayLink! Linda wallet yako ya kifedha kwa kuwezesha Fingerprint na kuthibitisha hati zako za KYC kwenye sehemu ya Wasifu."
    )

    fun getString(key: String, lang: String): String {
        val strings = if (lang == "sw") sw else en
        return strings[key] ?: en[key] ?: key
    }
}
